### ISSUE TITLE
执行 unpub --database mongodb: 报错

### ISSUE THREAD

**Issue by shiqianren** [bytedance/unpub#11]
```
SocketException: OS Error: Connection refused, errno = 61, address = 10.***.**, port = 52157
#0      _ConnectionManager._connect (package:mongo_dart/src/network/connection_manager.dart:23:5)
<asynchronous suspension>
#1      _ConnectionManager.open.<anonymous closure> (package:mongo_dart/src/network/connection_manager.dart:58:14)
#2      Future.forEach.<anonymous closure> (dart:async/future.dart:492:26)
#3      Future.doWhile.<anonymous closure> (dart:async/future.dart:534:26)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#5      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1355:26)
#6      Future.doWhile (dart:async/future.dart:549:18)
#7      Future.forEach (dart:async/future.dart:490:12)
#8      _ConnectionManager.open (package:mongo_dart/src/network/connection_manager.dart:56:19)
#9      Db.open.<anonymous closure> (package:mongo_dart/src/database/db.dart:220:33)
#10     new Future.sync (dart:async/future.dart:224:31)
#11     Db.open (package:mongo_dart/src/database/db.dart:207:19)
#12     main (file:///Users/renshiqian/.pub-cache/hosted/pub.flutter-io.cn/unpub-1.2.1/bin/unpub.dart:28:23)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by pd4d10** [comment]
这个问题还有吗？看起来像是数据库没有连接上。

**Comment by pd4d10** [comment]
Closing. Feel free to reopen if the problem still exists
