### ISSUE TITLE
Failed to publish package using Melos

### ISSUE THREAD

**Issue by dangvinh** [bytedance/unpub#81]
Hi,
I'm using [Melos](https://github.com/invertase/melos) to manage my packages in one mono-repo,

But, when I publish package to self-hosted (**unpub**), it's through error:
```
Reading pub registry for package information... SUCCESS
Unhandled exception:
FormatException: Unexpected character (at character 1)
<!DOCTYPE html>
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:612:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      Package.getPublishedVersions (package:melos/src/package.dart:770:15)
<asynchronous suspension>
#7      _PublishMixin._getLatestPublishedVersionForPackages.<anonymous closure> (package:melos/src/commands/publish.dart:109:24)
<asynchronous suspension>
#8      Pool.forEach.run (package:pool/pool.dart:183:19)
<asynchronous suspension>
#9      Pool.withResource (package:pool/pool.dart:127:14)
<asynchronous suspension>
#10     Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
<asynchronous suspension>
```

I have researched, and it's seem as an Unpub bug.
Note: it's related to this issue: https://github.com/invertase/melos/issues/307

**Comment by talisk** [comment]
It looks like the api `<pub-server>/packages/<package-name>.json` returned an invalid result. Could you paste the response body of the api? @dangvinh

**Comment by pontus-andersson** [comment]
@dangvinh any updates on this? We're investigating if it's possible to use `unpub` with `melos` atm. 
Let me know if we can help out with something.

**Comment by ahmdaeyz** [comment]
Hey @pontus-andersson,
I'm also investigating the possibility of using unpub with melos, Were you able to do that without any issues?

**Comment by pontus-andersson** [comment]
> Hey @pontus-andersson,
> 
> I'm also investigating the possibility of using unpub with melos, Were you able to do that without any issues?

Not yet, unfortunately.
